### ISSUE TITLE
Mixed Content error

### ISSUE THREAD

**Issue by ChaseLEngel** [sidd/serene#9]
These two errors are repeatedly logged to the console every couple of seconds. It starts as soon as the login page is loaded.
Version: v0.0.6

Mixed Content: The page at 'https://[URL]/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://[URL]:7000/sockjs-node/info?t=1452744035508'. This request has been blocked; the content must be served over HTTPS.
	AbstractXHRObject._start	@	bundle.js:4130
	(anonymous function)	@	bundle.js:4023

[WDS] Disconnected!
	sock.onclose @ bundle.js:626
	EventTarget.dispatchEvent @ bundle.js:3565
	(anonymous function) @ bundle.js:6715

**Comment by sidd** [comment]
Thanks, looks like I left hot module replacement in the production build (it's just trying to connect to the server, which does not exist). [This plugin](https://github.com/sidd/serene/blob/master/webpack.config.js#L43) should only be loaded when `process.env.NODE_ENV !== 'production'`.

Fixed in next release.

**Comment by sidd** [comment]
Fixed in 0.0.7.
